- Fix the functional test error as below:
******* Functional Test *******
TestName: runTest
ErrorType: exceptions.ImportError
ErrorMessage: cannot import name main
TestName: runTest
ErrorType: exceptions.ImportError
ErrorMessage: cannot import name main

- Missing infrasim bin file

- Update version test command

- Update setup.cfg to install bin/infrasim